### ISSUE TITLE
Async client support

### ISSUE THREAD

**Issue by pkulev** [moonburnt/hscp#3]
While it's working solution to use synchronous client in separate thread, it's a good idea to provide AsyncClient for those fancy asyncio folks.

**Comment by moonburnt** [comment]
will this do? https://github.com/moonburnt/hscp/commit/d6a1362fee11cd671a4c0713c7eee37d0a231d28

**Comment by moonburnt** [comment]
Implemented in https://github.com/moonburnt/hscp/commit/cb2d4f67ca11b5548845a7c7fe323cf2a23785bf

**Comment by pkulev** [comment]
Yep, thanks <3
